In [ ]:
import sklearn.linear_model as lm
import pandas as pd
data=pd.read_csv("pizza.csv")
print(data)

    rec  x1    x2      y
0     1   2  0.50   9.95
1     1   8  1.10  24.45
2     1  11  1.20  31.75
3     1  10  5.50  35.00
4     1   8  2.95  25.02
5     1   4  2.00  16.86
6     1   2  3.75  14.38
7     1   2  0.52   9.60
8     1   9  1.00  24.35
9     1   8  3.00  27.50
10    1  14  4.12  17.08
11    1  11  4.00  37.00
12    1  12  5.00  41.95
13    1   2  3.60  11.66
14    1   4  2.05  21.65
15    1   4  4.00  17.89
16    1  20  6.00  69.00
17    1   1  5.85  10.30
18    1  10  5.40  34.93
19    1  15  2.50  46.59
20    1  15  2.90  44.88
21    1  16  5.10  54.12
22    1  17  5.90  56.23
23    1   6  1.00  22.13
24    1   5  4.00  21.15


In [ ]:
var_index=['x1','x2']
x=data[var_index]
print(x)

    x1    x2
0    2  0.50
1    8  1.10
2   11  1.20
3   10  5.50
4    8  2.95
5    4  2.00
6    2  3.75
7    2  0.52
8    9  1.00
9    8  3.00
10  14  4.12
11  11  4.00
12  12  5.00
13   2  3.60
14   4  2.05
15   4  4.00
16  20  6.00
17   1  5.85
18  10  5.40
19  15  2.50
20  15  2.90
21  16  5.10
22  17  5.90
23   6  1.00
24   5  4.00


In [ ]:
y=data['y']
print(y)

0      9.95
1     24.45
2     31.75
3     35.00
4     25.02
5     16.86
6     14.38
7      9.60
8     24.35
9     27.50
10    17.08
11    37.00
12    41.95
13    11.66
14    21.65
15    17.89
16    69.00
17    10.30
18    34.93
19    46.59
20    44.88
21    54.12
22    56.23
23    22.13
24    21.15
Name: y, dtype: float64


In [ ]:
lr=lm.LinearRegression()
lr.fit(x,y)
print("coef:",lr.coef_)

coef: [2.51542374 1.23997126]


In [ ]:
print("intercept",lr.intercept_)

intercept 3.169810241507406


In [ ]:
print("persamaan regresi yg didapat:")
print("y = {0:.2f} + {0:.2f} {0:.2f}".format(lr.intercept_,lr.coef_[0],lr.coef_[1]))
print("y = {} + {} {}".format(lr.intercept_,lr.coef_[0],lr.coef_[1]))

persamaan regresi yg didapat:
y = 3.17 + 3.17 3.17
y = 3.169810241507406 + 2.515423740298575 1.2399712570270385


In [ ]:
import pandas as pd
import numpy as np

data=pd.read_csv("pizza.csv")
print(data)

    rec  x1    x2      y
0     1   2  0.50   9.95
1     1   8  1.10  24.45
2     1  11  1.20  31.75
3     1  10  5.50  35.00
4     1   8  2.95  25.02
5     1   4  2.00  16.86
6     1   2  3.75  14.38
7     1   2  0.52   9.60
8     1   9  1.00  24.35
9     1   8  3.00  27.50
10    1  14  4.12  17.08
11    1  11  4.00  37.00
12    1  12  5.00  41.95
13    1   2  3.60  11.66
14    1   4  2.05  21.65
15    1   4  4.00  17.89
16    1  20  6.00  69.00
17    1   1  5.85  10.30
18    1  10  5.40  34.93
19    1  15  2.50  46.59
20    1  15  2.90  44.88
21    1  16  5.10  54.12
22    1  17  5.90  56.23
23    1   6  1.00  22.13
24    1   5  4.00  21.15


In [ ]:
data2=data.to_numpy()

print(data2)

[[ 1.    2.    0.5   9.95]
 [ 1.    8.    1.1  24.45]
 [ 1.   11.    1.2  31.75]
 [ 1.   10.    5.5  35.  ]
 [ 1.    8.    2.95 25.02]
 [ 1.    4.    2.   16.86]
 [ 1.    2.    3.75 14.38]
 [ 1.    2.    0.52  9.6 ]
 [ 1.    9.    1.   24.35]
 [ 1.    8.    3.   27.5 ]
 [ 1.   14.    4.12 17.08]
 [ 1.   11.    4.   37.  ]
 [ 1.   12.    5.   41.95]
 [ 1.    2.    3.6  11.66]
 [ 1.    4.    2.05 21.65]
 [ 1.    4.    4.   17.89]
 [ 1.   20.    6.   69.  ]
 [ 1.    1.    5.85 10.3 ]
 [ 1.   10.    5.4  34.93]
 [ 1.   15.    2.5  46.59]
 [ 1.   15.    2.9  44.88]
 [ 1.   16.    5.1  54.12]
 [ 1.   17.    5.9  56.23]
 [ 1.    6.    1.   22.13]
 [ 1.    5.    4.   21.15]]


In [ ]:
X=data2[:,0:3]

print(X)

[[ 1.    2.    0.5 ]
 [ 1.    8.    1.1 ]
 [ 1.   11.    1.2 ]
 [ 1.   10.    5.5 ]
 [ 1.    8.    2.95]
 [ 1.    4.    2.  ]
 [ 1.    2.    3.75]
 [ 1.    2.    0.52]
 [ 1.    9.    1.  ]
 [ 1.    8.    3.  ]
 [ 1.   14.    4.12]
 [ 1.   11.    4.  ]
 [ 1.   12.    5.  ]
 [ 1.    2.    3.6 ]
 [ 1.    4.    2.05]
 [ 1.    4.    4.  ]
 [ 1.   20.    6.  ]
 [ 1.    1.    5.85]
 [ 1.   10.    5.4 ]
 [ 1.   15.    2.5 ]
 [ 1.   15.    2.9 ]
 [ 1.   16.    5.1 ]
 [ 1.   17.    5.9 ]
 [ 1.    6.    1.  ]
 [ 1.    5.    4.  ]]


In [ ]:
Y=data2[:,3]

print(Y)

[ 9.95 24.45 31.75 35.   25.02 16.86 14.38  9.6  24.35 27.5  17.08 37.
 41.95 11.66 21.65 17.89 69.   10.3  34.93 46.59 44.88 54.12 56.23 22.13
 21.15]


In [ ]:
Xt=X.transpose()

print(Xt)

[[ 1.    1.    1.    1.    1.    1.    1.    1.    1.    1.    1.    1.
   1.    1.    1.    1.    1.    1.    1.    1.    1.    1.    1.    1.
   1.  ]
 [ 2.    8.   11.   10.    8.    4.    2.    2.    9.    8.   14.   11.
  12.    2.    4.    4.   20.    1.   10.   15.   15.   16.   17.    6.
   5.  ]
 [ 0.5   1.1   1.2   5.5   2.95  2.    3.75  0.52  1.    3.    4.12  4.
   5.    3.6   2.05  4.    6.    5.85  5.4   2.5   2.9   5.1   5.9   1.
   4.  ]]


In [ ]:
XtX=Xt.dot(X)

print(XtX)

[[  25.      216.       82.94  ]
 [ 216.     2576.      812.97  ]
 [  82.94    812.97    353.1848]]


In [ ]:
XtI=np.linalg.inv(XtX)

print(XtI)

[[ 0.21599448 -0.00768933 -0.03302346]
 [-0.00768933  0.00169281 -0.00209084]
 [-0.03302346 -0.00209084  0.01539918]]


In [ ]:
XtY=Xt.dot(Y)

print(XtY)

[ 725.42   8172.47   2745.8071]


In [ ]:
b=XtI.dot(XtY)

print(b)

[3.16981024 2.51542374 1.23997126]


In [ ]:
print("y = {} + {} {}".format(b[0],b[1],b[2]))

y = 3.1698102415073715 + 2.5154237402985773 1.2399712570270325
